repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        args: [--fix, --exit-non-zero-on-fix, --quiet]
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        args: [--quiet]
        language: system
        types_or: [python, pyi]
        require_serial: true

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss]
        additional_dependencies:
          - prettier@3.4.2
          - prettier-plugin-organize-imports@4.1.0

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: cd frontend && npx eslint
        language: system
        types: [javascript, jsx, ts, tsx]
        files: \.(js|jsx|ts|tsx)$