services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-6080}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    restart: always

  backend:
    build: 
      context: ./backend
      target: ${ENVIRONMENT:-development}
    env_file:
      - ./.env.example
      - ./.env
    command: bash /pyspur/backend/entrypoint.sh
    volumes:
      - .:/pyspur
      - ./.env:/pyspur/backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: 
      context: ./frontend
      target: ${ENVIRONMENT:-development}
    env_file:
      - ./.env.example
      - ./.env
    command: npm run dev
    volumes:
      - .:/pyspur
      - /pyspur/frontend/node_modules
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:17-alpine
    restart: on-failure
    env_file:
      - ./.env.example
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ['CMD-SHELL', 'pg_isready -U pyspur']
        interval: 5s
        timeout: 5s
volumes:
  node_modules:
  postgres_data:
