version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "6080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - backend
      - frontend
    restart: always
  backend:
    build: ./backend
    command: bash /pyspur/entrypoint.sh
    volumes:
      - ./backend:/pyspur
    restart: always
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
volumes:
  node_modules:
