version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "6080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - backend
      - frontend
  backend:
    build: ./backend
    command: bash /pyspur/entrypoint.sh
    volumes:
      - ./backend:/pyspur
    ports:
      - "8000:8000"
      - "8787:8787"
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  node_modules: