services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-6080}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - backend
      - frontend
    restart: always

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-pyspur-dev/pyspur}-backend:${VERSION:-latest}
    command: bash /pyspur/backend/entrypoint.sh
    volumes:
      - ./.env:/pyspur/backend/.env
      - ${SQLITE_DB_PATH:-./backend/sqlite/}:/pyspur/backend/sqlite/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-pyspur-dev/pyspur}-frontend:${VERSION:-latest}
    command: npm run start
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - FRONTEND_HOST=${FRONTEND_HOST:-0.0.0.0}
    depends_on:
      - backend
    restart: always 