services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-pyspur-dev/pyspur}-backend:${VERSION:-latest}
    command: bash /pyspur/backend/entrypoint.sh
    ports:
      - "${PYSPUR_PORT:-6080}:8000"
    env_file:
      - ./.env.example
      - ./.env
    volumes:
      - ./.env:/pyspur/backend/.env
      - pyspur_data:/pyspur/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SOCKET_MODE_DISABLED=true

  slack-socket-worker:
    build:
      context: .
      dockerfile: Dockerfile.socket
    env_file:
      - ./.env.example
      - ./.env
    volumes:
      - ./.env:/app/.env
      - pyspur_data:/app/data
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    deploy:
      replicas: ${SOCKET_WORKERS:-2}
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    restart: on-failure
    env_file:
      - ./.env.example
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ['CMD-SHELL', 'pg_isready -U pyspur']
        interval: 5s
        timeout: 5s
volumes:
  postgres_data:
  pyspur_data:  # Used to persist data like uploaded files, eval outputs, datasets