services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-6080}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    restart: always
  backend:
    build: 
      context: ./backend
      target: ${ENVIRONMENT:-development}
    command: bash /pyspur/backend/entrypoint.sh
    volumes:
      - .:/pyspur
      - ./.env:/pyspur/backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  frontend:
    build: 
      context: ./frontend
      target: ${ENVIRONMENT:-development}
    command: npm run dev
    volumes:
      - .:/pyspur
      - /pyspur/frontend/node_modules
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - FRONTEND_HOST=${FRONTEND_HOST:-0.0.0.0}
    depends_on:
      - backend
    restart: always
  db:
    image: postgres:17-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pyspur}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pyspur}
      - POSTGRES_DB=${POSTGRES_DB:-pyspur}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ['CMD-SHELL', 'pg_isready -U pyspur']
        interval: 5s
        timeout: 5s
volumes:
  node_modules:
  postgres_data:
