version: '3.8'

services:
  api:
    build: ./backend
    command: bash /app/entrypoint.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
      - "8787:8787"
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  node_modules: