services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-6080}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    restart: always
  backend:
    build: 
      context: ./backend
      target: ${ENVIRONMENT:-development}
    command: bash /pyspur/backend/entrypoint.sh
    volumes:
      - .:/pyspur
      - ./.env:/pyspur/backend/.env
      - ${SQLITE_DB_PATH:-./backend/sqlite/}:/pyspur/backend/sqlite/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  frontend:
    build: 
      context: ./frontend
      target: ${ENVIRONMENT:-development}
    command: npm run dev
    volumes:
      - .:/pyspur
      - /pyspur/frontend/node_modules
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - FRONTEND_HOST=${FRONTEND_HOST:-0.0.0.0}
    depends_on:
      - backend
    restart: always
volumes:
  node_modules:
